### ISSUE TITLE
Update connector and pravega snapshot version to pull from jcenter

### ISSUE THREAD

**Issue by vijikarthi** [pravega/nautilus-samples#23]
The `develop` branch is currently pointing to connector version `0.3.0-SNAPSHOT`. Building `nautilus-samples` will fail unless the connector dependency is available locally (by building the connector build from master branch and publishing it to local repository `$CONNECTOR_HOME/gradlew clean install`).

Since the snapshot version of the connector artifacts are now published to jcenter repo (`https://oss.jfrog.org/jfrog-dependencies/io/pravega/pravega-connectors-flink_2.11/`), we can update the connector version from `0.3.0-SNAPSHOT` to the most recent SNAPSHOT version published in  jcenter repo.

Make sure both `anomaly-samples` and `pravega-samples` application work with the latest connector snapshot.

**Comment by EronWright** [comment]
Partial progress made via #25

**Comment by vijikarthi** [comment]
closed https://github.com/pravega/nautilus-samples/pull/28
