### ISSUE TITLE
do not exclude gradlew and related files from sourceZip task

### ISSUE THREAD

**Issue by sarlaccpit** [pravega/nautilus-samples#32]
When consuming the result of the sourceZip task, the result is the source tree but without gradlew, which causes extra manual steps to be able to compile an unzipped tree of the source.

https://github.com/pravega/nautilus-samples/blob/master/build.gradle#L75-L76

Leaving those in when zipping up the source tree would be helpful.

**Comment by vijikarthi** [comment]
closed https://github.com/pravega/nautilus-samples/pull/31
